language: python
python:
  - 2.7

env:
  matrix:
    - DB_ENGINE=mongodb
    - DB_ENGINE=elasticsearch

before_install:
  # start proper service
  - if [[ "$DB_ENGINE" == "mongodb" ]]; then sudo service mongodb start; fi
  - if [[ "$DB_ENGINE" == "elasticsearch" ]]; then sudo service elasticsearch start; fi
  # install Python dependencies
  - if [[ "$DB_ENGINE" == "mongodb" ]]; then pip install pymongo; fi
  - if [[ "$DB_ENGINE" == "elasticsearch" ]]; then pip install elasticsearch; fi
  - pip install bottle
  - pip install httplib2
  - pip install voluptuous
  # export proper configuration file
  - if [[ "$DB_ENGINE" == "mongodb" ]]; then export SERVICE_CONFIG_FILE=./config/services.mongodb.conf; fi
  - if [[ "$DB_ENGINE" == "elasticsearch" ]]; then export SERVICE_CONFIG_FILE=./config/services.elasticsearch.conf; fi
  - pip install nose-exclude

install:
  - python setup.py install
  - .travis-data/run_dbservice_daemon.sh

before_script:
  - if [[ "$DB_ENGINE" == "mongodb" ]]; then export EXCLUDE_TEST_MODULE=elasticsearch; fi
  - if [[ "$DB_ENGINE" == "elasticsearch" ]]; then export EXCLUDE_TEST_MODULE=mongo; fi

script:
  - nosetests -v -w test --ignore-file=$EXCLUDE_TEST_MODULE
